baseURL = "http://localhost/"
languageCode = "en-us"
title = "SourceApprentice"
theme = "j-solarized"
paginate = 500
pygmentsStyle = "solarized-light" # solarized-light, -dark or -dark256
pygmentsUseClasses = "True"
copyright = ""

[params]
  domain = "localhost"
  scheme = "light" # light, dark or gray
  description = "Linux, Containers ( Docker ), Orchestration ( Kubernetes ), DevOps (.*) -- Oh My!"
  dateFormat = "Jan 2, 2006"
  talkyardServerUrl = "https://comments-for-sourceapprentice-com.talkyard.net"
  talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"
  svg_data_type = "data-feather"
  svg_calendar = "calendar"
  svg_author = "feather"
  svg_tag = "tag"
  
[permalinks]
  blog = "/:filename/"

[related]
    [[related.indices]]
        name = "thread" # The name of the indice, same as Front Matter's .Param key.
        weight = 1 # We don't really need this, but omitting it would disable the indice.
        includeNewer = true # Here our relationship is timeless! This prevents Hugo from ignoring newer posts.

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    pre = "info"
    url = "/about/"
    weight = 4

#[taxonomies]
#  tag = "tags"
