[params]
    svg_calendar = "calendar-outline"
    svg_author = "edit-2-outline"
    svg_tag = "hash-outline"
    svg_clock = "clock-outline"
    svg_data_type = "data-eva"

# See https://akveo.github.io/eva-icons/#/?type=outline
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home-outline"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit-outline"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "hash-outline"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    pre = "info-outline"
    url = "/about/"
    weight = 4